import Head from 'next/head'
import ChartWrapper from '../components/ChartWrapper';
import styles from '@/styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>D3 Sandbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       {/* D3 Sandbox */}
       <ChartWrapper />
      </main>
    </>
  )
}
